#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf ~/.tmux.conf

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/fish/config.fish
ln -s $DOTFILES/fish/config.fish $HOME/.config/fish/config.fish

rm -rf $HOME/.gitconfig
ln -s $DOTFILES/.gitconfig $HOME/.gitconfig

rm -rf $HOME/.gitignore
ln -s $DOTFILES/.gitignore $HOME/.gitignore

terminfo="~/.terminfo/"
[ ! -d $terminfo ] && echo "Directory  DOES NOT exists."

if [ ! -d $terminfo ]; then
    tempfile=$(mktemp) \
    && curl -o $tempfile https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo \
    && tic -x -o ~/.terminfo $tempfile \
    && rm $tempfile
fi

