#!/usr/bin/env bash

project_path_file=$HOME/.project_path


if [[ $# -eq 1 ]]; then
    selected=$1
else
    if [[ -f $project_path_file ]]; then
        IFS=' ' read -r -a path_array <<< "$(cat $project_path_file)"
        for path in "${path_array[@]}"
        do
            expanded_path=$(eval echo "$path")
            found_items=$(find $expanded_path -maxdepth 1 -mindepth 1 -type d 2>/dev/null)
            echo $found_items
             if [[ ! -z "$found_items" ]]; then
                 items+="$found_items\n"
             fi
        done  
        items+="/tmp"
        selected=$(echo -e "$items" | fzf)
        echo "Selected: $selected"
    else
        read -p "$project_path_file is not exsist."
        exit
    fi
fi

dirname=`basename $selected | sed 's/\./_/g'`

tmux switch-client -t =$dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
